# Generated by Django 4.2.1 on 2023-07-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
