# Generated by Django 4.2.4 on 2023-08-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_request_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='sendrequest',
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.CharField(max_length=500),
        ),
    ]
